### ISSUE TITLE
라이브러리 릴리즈 프로세스 확립

### ISSUE THREAD

**Issue by rscarrera27** [callsign-viper/Environment#1]
- 버저닝
- 릴리즈 주기/기준
- 기타 등등

**Comment by JoMingyu** [comment]
## 준비
- 아이디어 발의
- 이름(또는 가제) 정하기
- Idea-park에 이슈로 추가

## Team
- maintainer 모집(스케일에 따라 인원 수는 변동)
- Idea-park 이슈에 maintainer들 assignee 추가
- 담당자 선정
    - 로직 리드 개발자
    - 테스터
    - 리뷰어, 리팩토링

## Repository
- 레포 생성
- .gitignore 적용
- 라이센스 적용
- 아주 기본적인 README.md

## 개발 전
- 타겟 파이썬 버전 선정
- setup.py(author는 아이디어 발의자로, maintainer는 viper로)
- API 디자인

## 개발
- requirements.txt나 pipenv로 의존성 관리
- 로직 작성
- 테스트 코드 작성

## 서드파티
- CI
- Coverage(coveralls, codecov, ...)
- Code Quality

## 릴리즈 준비
- 문서화(sphinx, ...)
- 팀 전체에 리뷰 요청
- README 정리

```
릴리즈!
```

**Comment by JoMingyu** [comment]
## 버저닝 룰
버그 픽스 - 0.0.x
기능의 로직적 변경 - 0.x.0
함수 이름이 바뀌는 등의 대격변 - x.0.0

**Comment by JoMingyu** [comment]
추후에 변동사항 생기면 계속계속 추가하는걸로~
